# Generated by Django 3.0.5 on 2020-05-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_auto_20200525_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
        ),
    ]
