# Generated by Django 3.0.5 on 2020-05-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_auto_20200525_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
