# Generated by Django 3.0.5 on 2020-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_auto_20200606_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feed_photos'),
        ),
    ]
